In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [13]:
file = "Populationdata.csv"
file_df = pd.read_csv(file,encoding = "ISO-8859-1")
file_df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Arab World,ARB,"Population, total",SP.POP.TOTL,9.249093e+07,9.504450e+07,9.768229e+07,1.004111e+08,1.032399e+08,1.061750e+08,...,3.481451e+08,3.565089e+08,3.648959e+08,3.733070e+08,3.817021e+08,3.900430e+08,3.983050e+08,4.064527e+08,4.144919e+08,NaN
1,Caribbean small states,CSS,"Population, total",SP.POP.TOTL,4.198307e+06,4.277802e+06,4.357746e+06,4.436804e+06,4.513246e+06,4.585777e+06,...,6.939534e+06,6.984096e+06,7.029022e+06,7.074129e+06,7.118888e+06,7.162679e+06,7.204948e+06,7.245472e+06,7.284294e+06,NaN
2,Central Europe and the Baltics,CEB,"Population, total",SP.POP.TOTL,9.140176e+07,9.223274e+07,9.300950e+07,9.384002e+07,9.471580e+07,9.544099e+07,...,1.048005e+08,1.044214e+08,1.041740e+08,1.039353e+08,1.037137e+08,1.034962e+08,1.032578e+08,1.029943e+08,1.027353e+08,NaN
3,Early-demographic dividend,EAR,"Population, total",SP.POP.TOTL,9.792874e+08,1.002524e+09,1.026587e+09,1.051415e+09,1.077037e+09,1.103433e+09,...,2.865440e+09,2.909411e+09,2.953406e+09,2.997066e+09,3.040701e+09,3.084236e+09,3.127579e+09,3.170658e+09,3.213428e+09,NaN
4,East Asia & Pacific,EAS,"Population, total",SP.POP.TOTL,1.040034e+09,1.043597e+09,1.058046e+09,1.083797e+09,1.109192e+09,1.135651e+09,...,2.192343e+09,2.207155e+09,2.221935e+09,2.237073e+09,2.252293e+09,2.267717e+09,2.283073e+09,2.298707e+09,2.314368e+09,NaN

In [15]:
file_df1 = file_df.loc[:,['Country Name','Country Code','Indicator Name','Indicator Code','2012','2013','2014','2015','2016','2017']]
file_df1.head()

,Country Name,Country Code,Indicator Name,Indicator Code,2012,2013,2014,2015,2016,2017
0,Arab World,ARB,"Population, total",SP.POP.TOTL,3.733070e+08,3.817021e+08,3.900430e+08,3.983050e+08,4.064527e+08,4.144919e+08
1,Caribbean small states,CSS,"Population, total",SP.POP.TOTL,7.074129e+06,7.118888e+06,7.162679e+06,7.204948e+06,7.245472e+06,7.284294e+06
2,Central Europe and the Baltics,CEB,"Population, total",SP.POP.TOTL,1.039353e+08,1.037137e+08,1.034962e+08,1.032578e+08,1.029943e+08,1.027353e+08
3,Early-demographic dividend,EAR,"Population, total",SP.POP.TOTL,2.997066e+09,3.040701e+09,3.084236e+09,3.127579e+09,3.170658e+09,3.213428e+09
4,East Asia & Pacific,EAS,"Population, total",SP.POP.TOTL,2.237073e+09,2.252293e+09,2.267717e+09,2.283073e+09,2.298707e+09,2.314368e+09

In [19]:
file_df1_sort = file_df1.sort_values(by=['2017'],ascending=False)
file_df1_sort

,Country Name,Country Code,Indicator Name,Indicator Code,2012,2013,2014,2015,2016,2017
46,World,WLD,"Population, total",SP.POP.TOTL,7.099312e+09,7.184861e+09,7.271058e+09,7.357234e+09,7.443811e+09,7.529719e+09
16,IDA & IBRD total,IBT,"Population, total",SP.POP.TOTL,5.957572e+09,6.036055e+09,6.114993e+09,6.194071e+09,6.273593e+09,6.353188e+09
25,Low & middle income,LMY,"Population, total",SP.POP.TOTL,5.887403e+09,5.965522e+09,6.044110e+09,6.122854e+09,6.202028e+09,6.281280e+09
31,Middle income,MIC,"Population, total",SP.POP.TOTL,5.242502e+09,5.303972e+09,5.365538e+09,5.426795e+09,5.488006e+09,5.548831e+09
15,IBRD only,IBD,"Population, total",SP.POP.TOTL,4.519456e+09,4.564827e+09,4.610015e+09,4.654723e+09,4.699240e+09,4.743252e+09
3,Early-demographic dividend,EAR,"Population, total",SP.POP.TOTL,2.997066e+09,3.040701e+09,3.084236e+09,3.127579e+09,3.170658e+09,3.213428e+09
27,Lower middle income,LMC,"Population, total",SP.POP.TOTL,2.764010e+09,2.805787e+09,2.847558e+09,2.889358e+09,2.931084e+09,2.972650e+09
45,Upper middle income,UMC,"Population, total",SP.POP.TOTL,2.478492e+09,2.498184e+09,2.517980e+09,2.537437e+09,2.556922e+09,2.576181e+09
4,East Asia & Pacific,EAS,"Population, total",SP.POP.TOTL,2.237073e+09,2.252293e+09,2.267717e+09,2.283073e+09,2.298707e+09,2.314368e+09
20,Late-demographic dividend,LTE,"Population, total",SP.POP.TOTL,2.209612e+09,2.223399e+09,2.237241e+09,2.250821e+09,2.264577e+09,2.278213e+09
5,East Asia & Pacific (excluding high income),EAP,"Population, total",SP.POP.TOTL,1.994651e+09,2.009173e+09,2.023837e+09,2.038411e+09,2.053299e+09,2.068308e+09
6,East Asia & Pacific (IDA & IBRD countries),TEA,"Population, total",SP.POP.TOTL,1.969763e+09,1.984153e+09,1.998686e+09,2.013133e+09,2.027896e+09,2.042783e+09
40,South Asia,SAS,"Population, total",SP.POP.TOTL,1.676615e+09,1.699310e+09,1.721855e+09,1.744200e+09,1.766394e+09,1.788389e+09
41,South Asia (IDA & IBRD),TSA,"Population, total",SP.POP.TOTL,1.676615e+09,1.699310e+09,1.721855e+09,1.744200e+09,1.766394e+09,1.788389e+09
19,IDA total,IDA,"Population, total",SP.POP.TOTL,1.438116e+09,1.471228e+09,1.504978e+09,1.539348e+09,1.574353e+09,1.609937e+09
88,China,CHN,"Population, total",SP.POP.TOTL,1.350695e+09,1.357380e+09,1.364270e+09,1.371220e+09,1.378665e+09,1.386395e+09
136,India,IND,"Population, total",SP.POP.TOTL,1.263066e+09,1.278562e+09,1.293859e+09,1.309054e+09,1.324171e+09,1.339180e+09
34,OECD members,OED,"Population, total",SP.POP.TOTL,1.259459e+09,1.267516e+09,1.275901e+09,1.284164e+09,1.292501e+09,1.300250e+09
14,High income,HIC,"Population, total",SP.POP.TOTL,1.211908e+09,1.219339e+09,1.226947e+09,1.234380e+09,1.241783e+09,1.248439e+09
37,Post-demographic dividend,PST,"Population, total",SP.POP.TOTL,1.082578e+09,1.087392e+09,1.092414e+09,1.097402e+09,1.102424e+09,1.106749e+09
18,IDA only,IDX,"Population, total",SP.POP.TOTL,9.631227e+08,9.849661e+08,1.007226e+09,1.029952e+09,1.053194e+09,1.076914e+09
44,Sub-Saharan Africa (IDA & IBRD countries),TSS,"Population, total",SP.POP.TOTL,9.270399e+08,9.527341e+08,9.790179e+08,1.005850e+09,1.033213e+09,1.061108e+09
42,Sub-Saharan Africa,SSF,"Population, total",SP.POP.TOTL,9.270399e+08,9.527341e+08,9.790179e+08,1.005850e+09,1.033213e+09,1.061108e+09
43,Sub-Saharan Africa (excluding high income),SSA,"Population, total",SP.POP.TOTL,9.269516e+08,9.526441e+08,9.789266e+08,1.005757e+09,1.033118e+09,1.061012e+09
24,Least developed countries: UN classification,LDC,"Population, total",SP.POP.TOTL,8.904235e+08,9.120940e+08,9.341923e+08,9.566311e+08,9.793879e+08,1.002486e+09
8,Europe & Central Asia,ECS,"Population, total",SP.POP.TOTL,8.945625e+08,8.987997e+08,9.031156e+08,9.074328e+08,9.116940e+08,9.154839e+08
38,Pre-demographic dividend,PRE,"Population, total",SP.POP.TOTL,7.835058e+08,8.067054e+08,8.304427e+08,8.546460e+08,8.792925e+08,9.043998e+08
13,Heavily indebted poor countries (HIPC),HPC,"Population, total",SP.POP.TOTL,6.664886e+08,6.854020e+08,7.047454e+08,7.244827e+08,7.446030e+08,7.651123e+08
26,Low income,LIC,"Population, total",SP.POP.TOTL,6.449019e+08,6.615506e+08,6.785721e+08,6.960585e+08,7.140223e+08,7.324486e+08
21,Latin America & Caribbean,LCN,"Population, total",SP.POP.TOTL,6.105479e+08,6.174957e+08,6.243355e+08,6.310626e+08,6.376639e+08,6.441247e+08
...,...,...,...,...,...,...,...,...,...,...
125,Grenada,GRD,"Population, total",SP.POP.TOTL,1.054810e+05,1.059090e+05,1.063600e+05,1.068230e+05,1.073170e+05,1.078250e+05
259,Virgin Islands (U.S.),VIR,"Population, total",SP.POP.TOTL,1.081910e+05,1.080440e+05,1.078840e+05,1.077100e+05,1.075100e+05,1.072680e+05
175,"Micronesia, Fed. Sts.",FSM,"Population, total",SP.POP.TOTL,1.035030e+05,1.037020e+05,1.040150e+05,1.044330e+05,1.049370e+05,1.055440e+05
56,Aruba,ABW,"Population, total",SP.POP.TOTL,1.025770e+05,1.031870e+05,1.037950e+05,1.043410e+05,1.048220e+05,1.052640e+05
53,Antigua and Barbuda,ATG,"Population, total",SP.POP.TOTL,9.677700e+04,9.782400e+04,9.887500e+04,9.992300e+04,1.009630e+05,1.020120e+05
216,Seychelles,SYC,"Population, total",SP.POP.TOTL,8.830300e+04,8.994900e+04,9.135900e+04,9.341900e+04,9.467700e+04,9.584300e+04
141,Isle of Man,IMN,"Population, total",SP.POP.TOTL,8.140600e+04,8.201300e+04,8.259000e+04,8.316700e+04,8.373700e+04,8.428700e+04
51,Andorra,AND,"Population, total",SP.POP.TOTL,8.243100e+04,8.078800e+04,7.922300e+04,7.801400e+04,7.728100e+04,7.696500e+04
102,Dominica,DMA,"Population, total",SP.POP.TOTL,7.204400e+04,7.240000e+04,7.277800e+04,7.316200e+04,7.354300e+04,7.392500e+04
68,Bermuda,BMU,"Population, total",SP.POP.TOTL,6.479800e+04,6.500100e+04,6.513900e+04,6.523900e+04,6.534100e+04,6.544100e+04
83,Cayman Islands,CYM,"Population, total",SP.POP.TOTL,5.752300e+04,5.837100e+04,5.917200e+04,5.996300e+04,6.076500e+04,6.155900e+04
124,Greenland,GRL,"Population, total",SP.POP.TOTL,5.681000e+04,5.648300e+04,5.629500e+04,5.611400e+04,5.618600e+04,5.617100e+04
50,American Samoa,ASM,"Population, total",SP.POP.TOTL,5.523000e+04,5.530700e+04,5.543700e+04,5.553700e+04,5.559900e+04,5.564100e+04
228,St. Kitts and Nevis,KNA,"Population, total",SP.POP.TOTL,5.259100e+04,5.316900e+04,5.373900e+04,5.428800e+04,5.482100e+04,5.534500e+04
193,Northern Mariana Islands,MNP,"Population, total",SP.POP.TOTL,5.371800e+04,5.403600e+04,5.446800e+04,5.481600e+04,5.502300e+04,5.514400e+04
171,Marshall Islands,MHL,"Population, total",SP.POP.TOTL,5.266300e+04,5.279300e+04,5.289800e+04,5.299400e+04,5.306600e+04,5.312700e+04
112,Faroe Islands,FRO,"Population, total",SP.POP.TOTL,4.866600e+04,4.874700e+04,4.884200e+04,4.896500e+04,4.911700e+04,4.929000e+04
219,Sint Maarten (Dutch part),SXM,"Population, total",SP.POP.TOTL,3.464000e+04,3.660700e+04,3.768500e+04,3.882400e+04,3.996900e+04,4.110900e+04
177,Monaco,MCO,"Population, total",SP.POP.TOTL,3.778300e+04,3.797100e+04,3.813200e+04,3.830700e+04,3.849900e+04,3.869500e+04
161,Liechtenstein,LIE,"Population, total",SP.POP.TOTL,3.654500e+04,3.683400e+04,3.712700e+04,3.740300e+04,3.766600e+04,3.792200e+04
247,Turks and Caicos Islands,TCA,"Population, total",SP.POP.TOTL,3.243100e+04,3.310800e+04,3.373900e+04,3.433900e+04,3.490000e+04,3.544600e+04
122,Gibraltar,GIB,"Population, total",SP.POP.TOTL,3.362300e+04,3.383100e+04,3.403800e+04,3.422800e+04,3.440800e+04,3.457100e+04
211,San Marino,SMR,"Population, total",SP.POP.TOTL,3.191400e+04,3.230300e+04,3.265700e+04,3.296000e+04,3.320300e+04,3.340000e+04
230,St. Martin (French part),MAF,"Population, total",SP.POP.TOTL,3.095900e+04,3.126400e+04,3.153000e+04,3.175400e+04,3.194900e+04,3.212500e+04
74,British Virgin Islands,VGB,"Population, total",SP.POP.TOTL,2.850900e+04,2.905600e+04,2.958800e+04,3.011300e+04,3.066100e+04,3.119600e+04
197,Palau,PLW,"Population, total",SP.POP.TOTL,2.075800e+04,2.092000e+04,2.109400e+04,2.128800e+04,2.150300e+04,2.172900e+04
184,Nauru,NRU,"Population, total",SP.POP.TOTL,1.027900e+04,1.082100e+04,1.185300e+04,1.247500e+04,1.304900e+04,1.287600e+04
248,Tuvalu,TUV,"Population, total",SP.POP.TOTL,1.072500e+04,1.081900e+04,1.090800e+04,1.100100e+04,1.109700e+04,1.119200e+04
33,Not classified,INX,"Population, total",SP.POP.TOTL,NaN,NaN,NaN,NaN,NaN,NaN
108,Eritrea,ERI,"Population, total",SP.POP.TOTL,NaN,NaN,NaN,NaN,NaN,NaN